### ISSUE TITLE
basal rate not appearing in nightscout after update to v2

### ISSUE THREAD

**Issue by MatthewMazaika** [jwoglom/tconnectsync#107]
After the update to v2, using my same auto-update configuration, the current basal rate is no longer visible in nightscout - basal seems to be reported, but does not have any units 

Before with basal rate
![20241008_022758](https://github.com/user-attachments/assets/50ae0682-8acd-4de1-a23c-feb58485fdb0)

After without basal rate
![Screenshot_20241008_022915_Chrome](https://github.com/user-attachments/assets/9b73e10e-304c-4d7d-9cf6-cc43fe67236c)

Logs show that BASAL is indeed enabled and BOLUS events are appearing correctly

**Comment by CJWTX** [comment]
It seems like the profile sync part of the newest tconnectsync version has some bugs and creates a bunch of times where the basal rate is set to zero in Nightscout.

My temporary solution for this is just to disable the profiles feature.

**Comment by jwoglom** [comment]
Thanks for the reports, weird things were definitely going on with the profile imports (I wasn't removing empty values which tandem was returning in the API, which created additional 0 unit basal profile segments). Update to the latest version and let me know if you continue to see weirdness.

Note also that if you have any other systems pushing pump profiles to Nightscout, like Loop, you'll need to disable one of them. I actually checked my personal instance of tconnectsync, and Loop (which I'm using as a Nightscout uploader for CGM data on an iPhone for when Dexcom Share is down) was fighting with tconnectsync to override the nightscout profile configuration.

**Comment by MatthewMazaika** [comment]
this is looking good now! thanks!
