### ISSUE TITLE
Cannot parse argument of type None

### ISSUE THREAD

**Issue by Xedek** [jwoglom/tconnectsync#13]
My tconnectsync was working fine until i did a split bolus for 75% now and 25% later over 2 hours...30 min in i decided to cancel the rest of the bolus.  here is the verbose output for the command prompt (i am running using docker on windows 10)

DEBUG:root:Set logging level to DEBUG
INFO:tconnectsync.process:Downloading t:connect ControlIQ data
Processing data between 2021-07-08 07:09:01.450854 and 2021-07-09 07:09:01.450854
DEBUG:tconnectsync.api:Instantiating new ControlIQApi
INFO:tconnectsync.api.controliq:Logging in to ControlIQApi...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): tconnect.tandemdiabetes.com:443
DEBUG:urllib3.connectionpool:https://tconnect.tandemdiabetes.com:443 "GET /login.aspx?ReturnUrl=%2F HTTP/1.1" 200 33507
DEBUG:urllib3.connectionpool:https://tconnect.tandemdiabetes.com:443 "POST /login.aspx?ReturnUrl=%2F HTTP/1.1" 302 148
DEBUG:urllib3.connectionpool:https://tconnect.tandemdiabetes.com:443 "POST /CookieCheck.aspx?ReturnUrl=%2F HTTP/1.1" 302 118
DEBUG:urllib3.connectionpool:https://tconnect.tandemdiabetes.com:443 "GET / HTTP/1.1" 200 167543
INFO:tconnectsync.api.controliq:Logged in to ControlIQApi successfully (expiration: 2021-07-09T15:09:02.176Z, in 7 hours, 59 minutes)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): tdcservices.tandemdiabetes.com:443
DEBUG:urllib3.connectionpool:https://tdcservices.tandemdiabetes.com:443 "GET /tconnect/controliq/api/therapytimeline/users/c6dfafb2-1dc0-47b4-9209-a985d311cf62?startDate=07-08-2021&endDate=07-09-2021 HTTP/1.1" 200 2049
INFO:tconnectsync.process:Downloading t:connect CSV data
DEBUG:tconnectsync.api:Instantiating new WS2Api
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): tconnectws2.tandemdiabetes.com:443
DEBUG:urllib3.connectionpool:https://tconnectws2.tandemdiabetes.com:443 "GET /therapytimeline2csv/c6dfafb2-1dc0-47b4-9209-a985d311cf62/07-08-2021/07-09-2021?format=csv HTTP/1.1" 200 32835
DEBUG:tconnectsync.process:{'DeviceType': 't:slim X2 Insulin Pump', 'SerialNumber': 'deleted'
', 'Description': 'EGV', 'EventDateTime': '2021-07-08T23:30:47', 'Readings (CGM / BGM)': '116'}
INFO:tconnectsync.process:Last CGM reading from t:connect: 2021-07-08T23:30:47-06:00 (1 hours, 38 minutes ago)
DEBUG:tconnectsync.process:No CSV basal data found
DEBUG:tconnectsync.sync.basal:ns_write_basal_events: querying for last uploaded entry
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): deleted.herokuapp.com:443
DEBUG:urllib3.connectionpool:https://deleted.herokuapp.com:443 "GET /api/v1/treatments?count=1&find%5BenteredBy%5D=Pump%20%28tconnectsync%29&find%5BeventType%5D=Temp%20Basal&ts=1625814557.7124944 HTTP/1.1" 200 269
INFO:tconnectsync.sync.basal:Last Nightscout basal upload: 2021-07-09T07:02:11+00:00
DEBUG:tconnectsync.sync.basal:ns_write_basal_events: added 0 events
DEBUG:tconnectsync.sync.bolus:ns_write_bolus_events: querying for last uploaded entry
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): deleted.herokuapp.com:443
DEBUG:urllib3.connectionpool:https://deleted.herokuapp.com:443 "GET /api/v1/treatments?count=1&find%5BenteredBy%5D=Pump%20%28tconnectsync%29&find%5BeventType%5D=Combo%20Bolus&ts=1625814558.1518533 HTTP/1.1" 200 198
INFO:tconnectsync.sync.bolus:Last Nightscout bolus upload: 2021-07-09T01:19:45+00:00
Traceback (most recent call last):
  File "/home/appuser/main.py", line 77, in <module>
    main()
  File "/home/appuser/main.py", line 73, in main
    added = process_time_range(tconnect, nightscout, time_start, time_end, args.pretend)
  File "/home/appuser/tconnectsync/process.py", line 72, in process_time_range
    added += ns_write_bolus_events(nightscout, bolusEvents, pretend=pretend)
  File "/home/appuser/tconnectsync/sync/bolus.py", line 46, in ns_write_bolus_events
    if last_upload_time and arrow.get(event["completion_time"]) <= last_upload_time:
  File "/.venv/lib/python3.9/site-packages/arrow/api.py", line 80, in get
    return _factory.get(*args, **kwargs)
  File "/.venv/lib/python3.9/site-packages/arrow/factory.py", line 228, in get
    raise TypeError("Cannot parse argument of type None.")
TypeError: Cannot parse argument of type None.

I also attached my csv, the last entry is the extended bolus that i canceled.  Since this error no boluses have been uploaded to my nightscout.
[tt-08072021_074258.xlsx](https://github.com/jwoglom/tconnectsync/files/6789521/tt-08072021_074258.xlsx)

**Comment by Xedek** [comment]
[tt-08072021_074258.xlsx](https://github.com/jwoglom/tconnectsync/files/6789521/tt-08072021_074258.xlsx)

**Comment by jwoglom** [comment]
Thanks for the bug report! I just pushed a new commit which should contain a hotfix for this specific error. Might take about an hour for the docker images to be regenerated if you are using those.

Medium-term, I'm hoping to add end-to-end tests to catch things like this earlier. Extended boluses and cancelled boluses are two specific scenarios which come to mind where the Tandem API returns data in a slightly different form than normal which hasn't been fully tested -- coincidentally your situation here encompassed both of those :)

Let me know if this fixes the problem and if so I'll close the issue.

**Comment by Xedek** [comment]
That solved the issue.  Thanks for the quick update!
