### ISSUE TITLE
feature: track Sleep and Exercise modes in Nightscout

### ISSUE THREAD

**Issue by jwoglom** [jwoglom/tconnectsync#18]
Example sleep mode schema from `api.controliq.therapy_timeline`:

```
'events': [{'continuation': None,
             'duration': 30660,
             'eventType': 1,
             'timeZoneId': 'America/Los_Angeles',
             'x': 1635150630}],
```

Event types are listed in TConnectEntry

**Comment by ChiSoxDev** [comment]
Checking to see if there is any progress on this issue? The start of sleep and exercise mode appears, but it doesn't stay in NightScout for the entire duration.
