### ISSUE TITLE
Documentation Order

### ISSUE THREAD

**Issue by t1diotac** [jwoglom/tconnectsync#21]
Hey,

Thank you so much for creating this project! 

I have one small piece of feedback on the documentation for Docker using the local copy method. I had to first copy the .env file into the build directory and then run the build commands in order for tconnectsync to see/use my .env file inside the container once it was running. The documentation has that step happening after the build is complete. 

I am unclear how to do a PR to update it and submit it, so I figure an issue report might be helpful.

Thanks again for all the work!
-Chad

**Comment by jwoglom** [comment]
I think the `--env-file` docker CLI option will propagate the environment variables to the container without needing to build the container with the .env file inside it. I updated the documentation to reflect this:

> Move the `.env` file you created earlier into this folder, and run:
> ```
> $ docker run --env-file=.env tconnectsync --check-login
> ```
>
> **NOTE:** If using the `--env-file` option to `docker run`, you may need to remove all quotation marks (`'` and `"`s) around values in the `.env` file for Docker to propagate the variables correctly.

Can you give this a shot and see if it works?

**Comment by t1diotac** [comment]
Works perfectly, thank you!
