### ISSUE TITLE
Any plans for Windows environments?

### ISSUE THREAD

**Issue by robmendez** [jwoglom/tconnectsync#25]
Apologies if this has been asked before, but I didn't see it as an open/closed issue.

Do you know of any way to run this under Windows? I was thinking of using a VM, but never had luck with VirtualBox.

TIA

**Comment by jwoglom** [comment]
I primarily run Linux and Mac systems, so this isn't something I have tested. It should be possible to run this within the Windows Subsystem for Linux (https://docs.microsoft.com/en-us/windows/wsl/install) by following the Linux instructions. Alternatively, I suspect that if you installed Python for Windows you would be able to run the application natively.

**Comment by jwoglom** [comment]
@robmendez I've added some basic instructions to the README for Windows. Please feel free to re-open this issue if the instructions don't work, or send a PR to improve the instructions!

**Comment by robmendez** [comment]
After working thru a few hiccups, I've made it to the "**Running Tconnectsync Continuously**" section.

However, I'm getting stuck at the following steps...

- sudo systemctl start supervisord
- _Failed to start supervisord.service: Unit supervisord.service not found._

If I remove the d at the end of the comment as follows:

- sudo systemctl start supervisor

It appears to work and I can continue.

In the "_Then use the supervisorctl command to manage the status of the tconnectsync program_" step, I don't get any response when I do:

- sudo supervisorctl status

And when I do:

- sudo supervisorctl start tconnectsync

I get the following:

- tconnectsync: ERROR (no such process)

Appreciate any help/guidance. TIA!

**Comment by JasonJShuler** [comment]
Personally I found it best to use the supervisor tutorials from other sites to get supervisor set up and running as well as adding tconnectsync. Granted I ended up just using my free Azure credits to run a tiny VM with this thing on it that's what I would recommend personally

**Comment by jwoglom** [comment]
@robmendez my guess is that the supervisord's configuration file doesn't include a `[program:tconnectsync]` section. Maybe it isn't reading files under `/etc/supervisor/conf.d`, if you set it up the way I did? If you can find supervisor's configuration file then you can just dump the tconnectsync program configuration in there, it doesn't have to be a separate file.

And interesting that supervisor doesn't have the "d" in your installation -- maybe it depends on the distro...

**Comment by jwoglom** [comment]
Also, FYI, it's a bit of a hack but you can also run tconnectsync with heroku: see https://github.com/jwoglom/tconnectsync-heroku. If you're on the free plan, you need an external thing like uptimerobot to actually trigger it because the heroku dyno goes to sleep. Nonetheless, i'm hoping it's an easier solution for folks familiar with running nightscout within heroku who don't have a linux/windows/macos system running 24/7 to run the software on.
