### ISSUE TITLE
Automatically update Nightscout basal profile settings from pump

### ISSUE THREAD

**Issue by jwoglom** [jwoglom/tconnectsync#29]
Tconnectsync should have an option to change Nightscout's built-in basal profile options based on the pump's current values.

**Comment by craigpress** [comment]
This would be really awesome. I manually entered my kids profile information into nightscout, but will have to update when we change settings.

**Comment by jwoglom** [comment]
Initial code to query for profile and pump settings is in https://github.com/jwoglom/tconnectsync/commit/fae1d4de2c870d96fe0c0f082fa44f70237b6991

There's remaining work to be done to actually upload these values into nightscout, hoping to get to this in the next week or two

**Comment by rankelly** [comment]
> 

Any progress on this part?

**Comment by rankelly** [comment]
Would be nice if they had an API to grab this data.

**Comment by jwoglom** [comment]
@rankelly unfortunately not, however I started on the baseline work to scrape pump settings out of a table inside the tconnect UI, so the work for this is about halfway done. I haven't spent as much time working on tconnectsync lately as I've been focused on https://github.com/jwoglom/pumpx2.

The work on that effort could one day remove the dependency on tconnect (and tconnectsync) entirely for pushing data to nightscout. Not dissimilar from how xDrip can publish directly to Nightscout using without Dexcom Share.

**Comment by jwoglom** [comment]
@craigpress @rankelly @t1diotac @justinswartz This has been implemented in tconnectsync v0.9.0! Simply enable the `PROFILES` features option (see https://github.com/jwoglom/tconnectsync#what-gets-synced for instructions). Profile names and values should be synced from the pump to Nightscout, as well as profile switches (by modifying the default profile). 

Please try it out! Once this has been tested a bit more widely, I'll enable this by default in tconnectsync.
