### ISSUE TITLE
pip3 install tconnectsync - Permission Error CentOS/RHEL/RockyLinux 8

### ISSUE THREAD

**Issue by t1diotac** [jwoglom/tconnectsync#48]
Hello,

To perform a pip3 install on CentOS/RHEL/Rocky Linux 8 (mostly an out-of-the-box server install) I had to:
`sudo dnf install python3`
as my "wheel" user. I then created a non-privileged, limited user for tconnectsync:
`sudo useradd -m t1d`
And sudo'd to that user:
`sudo su - t1d`

Finally, when initially installing tconnectsync I received:

> PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6'

I was able to get past this with:
`pip3 install --user tconnectsync`
Which should keep the entire install contained within my user's home directory. Easier for compartmentalizing apps, keeping the OS clean, and trying out different versions/installs/cleanup.

Hopefully that helps someone!

**Comment by jwoglom** [comment]
Closing since we got this added in the readme in #50
