### ISSUE TITLE
pip3 install tconnectsync installs older version

### ISSUE THREAD

**Issue by t1diotac** [jwoglom/tconnectsync#49]
Hello,

`pip3 install --user tconnectsync`

followed by
`tconnectsync --help`
shows

> Version 0.7.1

The latest on Github appears to be 0.8.2

Thanks!

**Comment by t1diotac** [comment]
I was able to get to the latest by upgrading Python from 3.6 to 3.9 and using the full path to the 3.9 pip:
As my wheel user:
`sudo dnf install python-39`

And then go back to my t1d user:
`sudo su - t1d`

And finally:
`/usr/bin/pip3.9 install --upgrade --user tconnectsync`

This pulls in the latest 0.8.2 version.

**Comment by jwoglom** [comment]
Glad you got this working... I dropped python 3.6 support in 0.7.2, all current versions require python 3.7+
