### ISSUE TITLE
unclear running commands 

### ISSUE THREAD

**Issue by LegendaryGeek** [jwoglom/tconnectsync#5]
it is hard to understand how to run this, such as, where do i put my .env file, and how do i put it there. ive tried what i could, but the only progress ive managed to make, creates an error i dont know if i can fix. 

if i tell docker desktop to put my `.env` anywhere else but `/.venv` i get
```
Processing data between 2021-04-02 22:32:38.304414 and 2021-04-03 22:32:38.304414

Downloading t:connect ControlIQ data

Traceback (most recent call last):

File "/home/appuser/main.py", line 64, in <module>

main()

File "/home/appuser/main.py", line 60, in main

added = process_time_range(tconnect, time_start, time_end, args.pretend)

File "/home/appuser/tconnectsync/process.py", line 35, in process_time_range

raise e

File "/home/appuser/tconnectsync/process.py", line 26, in process_time_range

ciqTherapyTimelineData = tconnect.controliq.therapy_timeline(time_start, time_end)

File "/home/appuser/tconnectsync/api/__init__.py", line 24, in controliq

self._ciq = ControlIQApi(self.email, self.password)

File "/home/appuser/tconnectsync/api/controliq.py", line 17, in __init__

self.login(email, password)

File "/home/appuser/tconnectsync/api/controliq.py", line 37, in login

raise ApiLoginException(req.status_code, 'Error logging in to t:connect. Check your login credentials.')

tconnectsync.api.common.ApiLoginException: Error logging in to t:connect. Check your login credentials.
```

but if i do tell it to put `.env` file in `/.venv` i get 
```
Traceback (most recent call last):

File "/home/appuser/main.py", line 5, in <module>

import arrow

ModuleNotFoundError: No module named 'arrow'
```

**Comment by jwoglom** [comment]
Hi,

You should typically place the .env folder inside the folder in which you checked out the repository. (i.e., the same folder as main.py). If you're using docker, you don't need to specify a .env file and can instead pass the environment variables you would specify in .env directly through docker. (e.g., specify environment variables for TCONNECT_EMAIL, etc.)

As for the second error, it looks like you just need to install some Python dependencies. Double-check that you have pipenv installed, then cd to the tconnectsync folder and run `pipenv install`. see https://github.com/jwoglom/tconnectsync/blob/master/README.md#running-with-pipenv

**Comment by LegendaryGeek** [comment]
okay, so i figured out what my issues was, but aparently didnt post a comment about my fix >.> 
how i fixed my issue, was editing the code. after doing everything i could, i found out it wasnt myfault. for some reason it wasnt getting the enviroment variables. i had to edit the code manually.
