### ISSUE TITLE
invalid token error

### ISSUE THREAD

**Issue by LegendaryGeek** [jwoglom/tconnectsync#6]
sadly, i lack the python knowledge to make a pr. the android api reports an api exception when the token expires, it reports the error on line 77, which i look and its because there is no catch to see if its because its an expired token error. anyway, here is the exact error from the docker console: 
```
Traceback (most recent call last):

File "/home/appuser/main.py", line 64, in <module>

main()

File "/home/appuser/main.py", line 57, in main

process_auto_update(tconnect, time_start, time_end, args.pretend)

File "/home/appuser/tconnectsync/autoupdate.py", line 23, in process_auto_update

last_event = tconnect.android.last_event_uploaded(PUMP_SERIAL_NUMBER)

File "/home/appuser/tconnectsync/api/android.py", line 91, in last_event_uploaded

return self.get('cloud/upload/getlasteventuploaded?sn=%d' % pump_serial_number)

File "/home/appuser/tconnectsync/api/android.py", line 77, in get

raise ApiException(r.status_code, "Internal API HTTP %s response: %s" % (str(r.status_code), r.text))

tconnectsync.api.common.ApiException: Internal API HTTP 401 response: {"statusCode":401,"status":401,"code":401,"message":"Invalid token: access token has expired","name":"invalid_token"}
```

**Comment by jwoglom** [comment]
Thanks for the report -- I have some existing code which looks at the timestamp that the android API provides as to when its API token will expire, but no explicit checks for a HTTP 401 exception.

No pressure to delve into the code for this, but in case you're curious I have the "check if token expired" logic here: https://github.com/jwoglom/tconnectsync/blob/c7aac1dca3b49a9f0a80f660a33ef8336d79f6a4/tconnectsync/api/android.py#L65

and it's invoked here: https://github.com/jwoglom/tconnectsync/blob/c7aac1dca3b49a9f0a80f660a33ef8336d79f6a4/tconnectsync/api/__init__.py#L37

**Comment by jwoglom** [comment]
I just pushed a bugfix related to this behavior, let me know if this solves the issue. https://github.com/jwoglom/tconnectsync/commit/8dcbee4280bc3ab9715c53c1a6af39a72bad97f0

**Comment by LegendaryGeek** [comment]
it appears to have been fixed, thank you

**Comment by LegendaryGeek** [comment]
```
New event index: 78386 last: 78303

Downloading t:connect ControlIQ data

Traceback (most recent call last):

File "/home/appuser/main.py", line 64, in <module>

main()

File "/home/appuser/main.py", line 57, in main

process_auto_update(tconnect, time_start, time_end, args.pretend)

File "/home/appuser/tconnectsync/autoupdate.py", line 31, in process_auto_update

added = process_time_range(tconnect, time_start, time_end, pretend)

File "/home/appuser/tconnectsync/process.py", line 35, in process_time_range

raise e

File "/home/appuser/tconnectsync/process.py", line 26, in process_time_range

ciqTherapyTimelineData = tconnect.controliq.therapy_timeline(time_start, time_end)

File "/home/appuser/tconnectsync/api/controliq.py", line 67, in therapy_timeline

return self.get('therapytimeline/users/%s' % (self.userGuid), {

File "/home/appuser/tconnectsync/api/controliq.py", line 57, in get

raise ApiException(r.status_code, "ControlIQ API HTTP %s response: %s" % (str(r.status_code), r.text))

tconnectsync.api.common.ApiException: ControlIQ API HTTP 401 response:
```
not sure what im looking at, but it looks a lot like it persists to the issue

**Comment by jwoglom** [comment]
Yeah, looks like there's some more handling required here. I'll look later today or tomorrow and try to publish a fix.

**Comment by jwoglom** [comment]
I published a new version with some fixes. Please take a look.

**Comment by LegendaryGeek** [comment]
okie, this issue persists no more, at least in this version
