### ISSUE TITLE
Python 3.9.9 is Not Available for Heroku-22 Stack - Heroku Not Compiling App

### ISSUE THREAD

**Issue by jwm5749** [jwoglom/tconnectsync#61]
I am getting the following error in my Heroku build log.  I see that Heroku has started building apps on the Heroku-22 stack.  I have Nightscout upgraded to the Heroku-22 stack and it is running well.  It appears that runtime 'Python-3.9.9' is not available for the Heroku-22 stack and is rejecting the push so it is not compiling the app.

-----> Building on the Heroku-22 stack
-----> Determining which buildpack to use for this app
-----> Python app detected
-----> Using Python version specified in runtime.txt
 !     Requested runtime 'python-3.9.9' is not available for this stack (heroku-22).
 !     For supported versions, see: https://devcenter.heroku.com/articles/python-support
 !     Push rejected, failed to compile Python app.
 !     Push failed

**To Reproduce**
1. Click Deploy to Heroku from Github
2. Fill In the Config Vars in Heroku
3. Click Deploy app
4. Wait and watch the build log

**Expected behavior**
I expected Heroku to deploy the app, but it gave me the copied error above in the build log instead.

**Have you followed the [Troubleshooting steps in the README?](https://github.com/jwoglom/tconnectsync-heroku#troubleshooting)** Yes

**Setup details**

* **On what platform are you using the t:connect mobile app?** Android
* **What version are you using of the t:connect mobile app?** 2.1.3

**Comment by jwoglom** [comment]
@jwm5749 Hi, thanks for the report -- this is hopefully a simple fix: https://github.com/jwoglom/tconnectsync-heroku/commit/c6aaf50fad1df018236210377a633642b3cb442d

Try following the [Updating to a new version instructions](https://github.com/jwoglom/tconnectsync-heroku#updating-to-a-new-version) and see if this resolves it

**Comment by jwm5749** [comment]
Up and running like a champ!!  Thank you for the quick answer and easy fix.  You are awesome!!!  Your projects are the best,  I am hoping pumpX2 develops to the point where I can use it to loop with AndroidAPS.  I am not much of a programmer but am a decent novice.  If you ever need any help that I can be of assistance I will be glad to help you anytime.  My contact info is on my profile page.
