### ISSUE TITLE
Issues with self-signed SSL cert on local install

### ISSUE THREAD

**Issue by ChristopherEnea** [jwoglom/tconnectsync#63]
**Describe the problem**
I am trying to run tconnectsync on a virtual machine in my homelab environment. I have nightscout running in docker and exposed on port 10443. Whenever I run --check-login I can see that tconnectsync will not connect to my nightscout instance because it is using a self-signed cert. 

I installed tconnectsync via Pip.

**To Reproduce**
1. Host nightscout with self-signed cert
2. Try to connect with tconnectsync

**Expected behavior**
Successful connection to nightscout.

**Setup details**
* **Operating system:** 
* Debian 11
* **tconnectsync version** (from `--version`): 
* 0.8.4
* **On what platform are you using the t:connect mobile app?** (Android or iOS)
* iOS
* **What version are you using of the t:connect mobile app?**
* 2.2

**Terminal output**
See next section

**Check Login output**
[tconnectsync-check-output.log](https://github.com/jwoglom/tconnectsync/files/9634775/tconnectsync-check-output.log)

**Additional context**
T:connect has not been uploading recently since I have a new phone with iOS 16.

**Comment by jwoglom** [comment]
You should now be able to bypass TLS certificate verification within tconnectsync for connecting to Nightscout via the `NS_SKIP_TLS_VERIFY` option in v0.8.5 and above.
