### ISSUE TITLE
API Errors: Error occurred querying WS2 therapy_timeline_csv / get() got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by rehudson** [jwoglom/tconnectsync#68]
**Describe the problem**
Hitting the URL I'm getting a lot of informaiton back, but I'm not seeing any information appear in Nightscout.  There are errors in the output.

**To Reproduce**
1. Loaded the URL with token

**Have you followed the [Troubleshooting steps in the README?](https://github.com/jwoglom/tconnectsync-heroku#troubleshooting)** (Yes or No)
Yes

**Setup details**

* **On what platform are you using the t:connect mobile app?** (Android or iOS): 
iOS
* **What version are you using of the t:connect mobile app?**

2.3.1

**Heroku log output**
If applicable, add the full output from the heroku logs in More > View Logs. ([See the instructions in the README.](https://github.com/jwoglom/tconnectsync-heroku#testing))
2022-11-05T13:34:07.545496+00:00 app[web.1]: API errors occurred. Please check the errors above.
2022-11-05T13:34:07.545496+00:00 app[web.1]: Created file tconnectsync-check-output.log containing additional debugging information.
2022-11-05T13:34:07.545497+00:00 app[web.1]: For support, you can upload this file to https://github.com/jwoglom/tconnectsync/issues/new
2022-11-05T13:34:07.545497+00:00 app[web.1]: The file -- but NOT the output printed above -- has been sanitized to remove sensitive data.
2022-11-05T13:34:07.545498+00:00 app[web.1]: Please verify and remove any sensitive data, such as your Nightscout URL/secret and pump serial number,
2022-11-05T13:34:07.545498+00:00 app[web.1]: as necessary.
2022-11-05T13:34:07.545521+00:00 app[web.1]: 
2022-11-05T13:34:07.551752+00:00 app[web.1]: 10.1.53.0 - - [05/Nov/2022:13:34:07 +0000] "GET /check_login?secret=5240ae1ff8c9324fc2886ff25b818177797854c223c4bfdf27cf02504c691dd9 HTTP/1.1" 200 396894 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
2022-11-05T13:39:21.068760+00:00 heroku[router]: at=info method=GET path="/" host=**********-tconnectsync.herokuapp.com request_id=635a8645-7a03-4188-a8d1-7c22a5e0c8f8 fwd="72.187.22.54" dyno=web.1 connect=0ms service=10ms status=200 bytes=563 protocol=https
2022-11-05T13:39:21.069183+00:00 app[web.1]: 10.1.27.205 - - [05/Nov/2022:13:39:21 +0000] "GET / HTTP/1.1" 200 409 "https://dashboard.heroku.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"

**Check Login output**
tconnectsync version 0.8.3
Python version 3.9.13 (main, May 24 2022, 21:31:40) 
[GCC 11.2.0]
System platform linux
Running checks with time range 2022-11-04 13:34:01.042832 to 2022-11-05 13:34:01.042832
Current time: 2022-11-05 13:34:01.042910
time.tzname: ('UTC', 'UTC')
Loading secrets...
TIMEZONE_NAME: America/New_York
-----
Logging in to t:connect ControlIQ API...
ControlIQ dashboard summary: 
{'averageDailySleepMinutes': 781,
 'averageReading': 132,
 'cgmInactiveMinutes': 0,
 'cgmInactivePercent': 0,
 'controlIqOffPercent': 0,
 'controlIqSetToOffMinutes': 0,
 'pumpInactiveMinutes': 0,
 'pumpInactivePercent': 0,
 'timeInUseMinutes': 1440,
 'timeInUsePercent': 100,
 'totalDays': 1,
 'weeklyExerciseEvents': 0}
tconnect_software_ver: t:connect 7.14.0.1
Querying ControlIQ therapy_timeline...
ControlIQ therapy_timeline: 
{'basal': {'algorithmDeliveryEvents': [{'duration': 199,
                                        'x': 1667545200,
                                        'y': 2.142},
                                       {'duration': 300,
                                        'x': 1667545399,
                                        'y': 2.192},
                                       {'duration': 298,
                                        'x': 1667545699,
                                        'y': 1.819},
  --SNIPPE---
                                        'x': 1667664566,
                                        'y': 0.793}],
           'profileDeliveryEvents': [],
           'profileRates': [{'duration': 199, 'x': 1667545200, 'y': 0.7},
                            {'duration': 21555, 'x': 1667545399, 'y': 0.75},
                            {'duration': 53910, 'x': 1667566954, 'y': 0.8},
                            {'duration': 10774, 'x': 1667620864, 'y': 0.7},
                            {'duration': 21848, 'x': 1667631638, 'y': 0.75},
                            {'duration': 11332, 'x': 1667653486, 'y': 0.8}],
           'tempDeliveryEvents': []},
 'events': [{'continuation': 'previous',
             'duration': 28862,
             'eventType': 1,
             'timeZoneId': 'America/Los_Angeles',
             'x': 1667545200},
            {'continuation': 'next',
             'duration': 51216,
             'eventType': 1,
             'timeZoneId': 'America/Los_Angeles',
             'x': 1667613602}],
 'pumpFeatures': [{'features': {'controlIQ': {'dateTimeFirstDetected': '2021-11-22T10:49:41',
                                              'feature': 1,
                                              'unixTimestamp': 1637578181}},
                   'serialNumber': '880757'}],
 'softwareUpdates': [],
 'suspensionDeliveryEvents': [{'continuation': None,
                               'suspendReason': 'control-iq',
                               'x': 1667564260},
                              {'continuation': None,
                               'suspendReason': 'control-iq',
                               'x': 1667612783},
                              {'continuation': None,
                               'suspendReason': 'control-iq',
                               'x': 1667614878},
                              {'continuation': None,
                               'suspendReason': 'control-iq',
                               'x': 1667623858},
                              {'continuation': None,
                               'suspendReason': 'control-iq',
                               'x': 1667633135},
                              {'continuation': None,
                               'suspendReason': 'control-iq',
                               'x': 1667648395},
                              {'continuation': None,
                               'suspendReason': 'control-iq',
                               'x': 1667655280}]}
------ HUGE Block of Text Snipped as github said comment was too long ----
            'eventDateTime': '2022-11-05T08:53:38',
            'eventID': 256,
            'eventTypeId': 0,
            'indexId': 0,
            'interactive': 0,
            'requestDateTime': '0001-01-01T00:00:00',
            'serialNumber': '880757',
            'sourceRecId': 0,
            'tempRateActivated': 0,
            'tempRateCompleted': 0,
            'tempRateId': 0,
            'type': 'CGM',
            'uploadId': 0},
           {'description': 'EGV',
            'deviceType': 't:slim X2 Insulin Pump',
            'egv': {'aboveTarget': 0,
                    'belowTarget': 0,
                    'estimatedGlucoseValue': 114,
                    'hyper': 0,
                    'hypo': 0,
                    'withinTarget': 1},
            'eventDateTime': '2022-11-05T08:58:38',
            'eventID': 256,
            'eventTypeId': 0,
            'indexId': 0,
            'interactive': 0,
            'requestDateTime': '0001-01-01T00:00:00',
            'serialNumber': '880757',
            'sourceRecId': 0,
            'tempRateActivated': 0,
            'tempRateCompleted': 0,
            'tempRateId': 0,
            'type': 'CGM',
            'uploadId': 0},
           {'description': 'EGV',
            'deviceType': 't:slim X2 Insulin Pump',
            'egv': {'aboveTarget': 0,
                    'belowTarget': 0,
                    'estimatedGlucoseValue': 114,
                    'hyper': 0,
                    'hypo': 0,
                    'withinTarget': 1},
            'eventDateTime': '2022-11-05T09:03:38',
            'eventID': 256,
            'eventTypeId': 0,
            'indexId': 0,
            'interactive': 0,
            'requestDateTime': '0001-01-01T00:00:00',
            'serialNumber': '880757',
            'sourceRecId': 0,
            'tempRateActivated': 0,
            'tempRateCompleted': 0,
            'tempRateId': 0,
            'type': 'CGM',
            'uploadId': 0},
           {'description': 'EGV',
            'deviceType': 't:slim X2 Insulin Pump',
            'egv': {'aboveTarget': 0,
                    'belowTarget': 0,
                    'estimatedGlucoseValue': 118,
                    'hyper': 0,
                    'hypo': 0,
                    'withinTarget': 1},
            'eventDateTime': '2022-11-05T09:08:38',
            'eventID': 256,
            'eventTypeId': 0,
            'indexId': 0,
            'interactive': 0,
            'requestDateTime': '0001-01-01T00:00:00',
            'serialNumber': '880757',
            'sourceRecId': 0,
            'tempRateActivated': 0,
            'tempRateCompleted': 0,
            'tempRateId': 0,
            'type': 'CGM',
            'uploadId': 0},
           {'description': 'EGV',
            'deviceType': 't:slim X2 Insulin Pump',
            'egv': {'aboveTarget': 0,
                    'belowTarget': 0,
                    'estimatedGlucoseValue': 110,
                    'hyper': 0,
                    'hypo': 0,
                    'withinTarget': 1},
            'eventDateTime': '2022-11-05T09:13:38',
            'eventID': 256,
            'eventTypeId': 0,
            'indexId': 0,
            'interactive': 0,
            'requestDateTime': '0001-01-01T00:00:00',
            'serialNumber': '880757',
            'sourceRecId': 0,
            'tempRateActivated': 0,
            'tempRateCompleted': 0,
            'tempRateId': 0,
            'type': 'CGM',
            'uploadId': 0}],
 'gapInData': 0,
 'noData': 0}
-----
Initializing t:connect WS2 API...
WS2 basaliq status: 
{'BasalIQTech': {'AverageGlucoseOnResume': 0,
                 'AverageSuspensionDuration': 0,
                 'AverageSuspensionsPerDay': 0,
                 'AvgGlucoseOnSuspend': 0,
                 'AvgInactiveDays': 0,
                 'AvgInactiveHours': 0,
                 'AvgInactiveMinutes': 0,
                 'BiqDaysSetOff': 0,
                 'BiqHoursSetOff': 0,
                 'BiqMinutesSetOff': 0,
                 'BiqPercentSetOff': 0,
                 'CgmInactiveDays': 0,
                 'CgmInactiveHours': 0,
                 'CgmInactiveMinutes': 0,
                 'CgmInactivePercent': 0,
                 'DaysOn': 0,
                 'DaysSuspendedDay': 0,
                 'DaysSuspendedNight': 0,
                 'HoursOn': 0,
                 'HoursSuspendedDay': 0,
                 'HoursSuspendedNight': 0,
                 'MinutesSuspendedDay': 0,
                 'MinutesSuspendedNight': 0,
                 'PercentSuspendedDay': 0,
                 'PercentSuspendedNight': 0,
                 'PercentTimeOn': 0,
                 'PumpInactiveDays': 2,
                 'PumpInactiveHours': 0,
                 'PumpInactiveMinutes': 0,
                 'PumpInactivePercent': 100}}
Querying WS2 therapy_timeline_csv...
Error occurred querying WS2 therapy_timeline_csv. This is okay so long as you are not using the PUMP_EVENTS or IOB sync features.
get() got an unexpected keyword argument 'timeout'
-----
Logging in to t:connect Android API...
Android user profile: 
{'age': 11,
 'caregiverDateOfBirth': '****',
 'caregiverFullName': 'Robert ',
 'dateOfBirth': '*******T00:00:00',
 'hasBASALIQ': False,
 'hasCGM': True,
 'hasControlIQ': True,
 'hyperThreshold': 171,
 'hypoThreshold': 60,
 'patientFullName': '*********',
 'targetBgHigh': 150,
 'targetBgLow': 70,
 'userID': '081b3701-3f3f-4f11-9a9e-c7d4bd709905'}
Android last uploaded event: 
{'maxPumpEventIndex': 872386, 'processingStatus': 1}
-----
Logging in to Nightscout...
Nightscout status: 
{'apiEnabled': True,
 'authorized': None,
 'boluscalcEnabled': False,
 'careportalEnabled': True,
 'extendedSettings': {'devicestatus': {'advanced': True, 'days': 1}},
 'name': 'nightscout',
 'runtimeState': 'loaded',
 'serverTime': '2022-11-05T13:34:07.208Z',
 'serverTimeEpoch': 1667655247208,
 'settings': {'DEFAULT_FEATURES': ['bgnow',
                                   'delta',
                                   'direction',
                                   'timeago',
                                   'devicestatus',
                                   'upbat',
                                   'errorcodes',
                                   'profile',
                                   'bolus',
                                   'dbsize',
                                   'runtimestate',
                                   'basal',
                                   'careportal'],
              'adminNotifiesEnabled': True,
              'alarmHigh': True,
              'alarmHighMins': [30, 60, 90, 120],
              'alarmLow': True,
              'alarmLowMins': [15, 30, 45, 60],
              'alarmPumpBatteryLow': False,
              'alarmTimeagoUrgent': True,
              'alarmTimeagoUrgentMins': '30',
              'alarmTimeagoWarn': True,
              'alarmTimeagoWarnMins': '15',
              'alarmTypes': ['simple'],
              'alarmUrgentHigh': True,
              'alarmUrgentHighMins': [30, 60, 90, 120],
              'alarmUrgentLow': True,
              'alarmUrgentLowMins': [15, 30, 45],
              'alarmUrgentMins': [30, 60, 90, 120],
              'alarmWarnMins': [30, 60, 90, 120],
              'authDefaultRoles': 'readable',
              'authFailDelay': 5000,
              'baseURL': '',
              'customTitle': ********
              'dayEnd': 21,
              'dayStart': 7,
              'deNormalizeDates': False,
              'editMode': True,
              'enable': ['careportal',
                         'bridge',
                         'alexa',
                         'iage',
                         'iob',
                         'sage',
                         'cob',
                         'maker',
                         'bwp',
                         'rawbg',
                         'pump',
                         'cage',
                         'basal',
                         'treatmentnotify',
                         'bgnow',
                         'delta',
                         'direction',
                         'timeago',
                         'devicestatus',
                         'upbat',
                         'errorcodes',
                         'profile',
                         'bolus',
                         'dbsize',
                         'runtimestate',
                         'simplealarms'],
              'focusHours': 3,
              'frameName1': '',
              'frameName2': '',
              'frameName3': '',
              'frameName4': '',
              'frameName5': '',
              'frameName6': '',
              'frameName7': '',
              'frameName8': '',
              'frameUrl1': '',
              'frameUrl2': '',
              'frameUrl3': '',
              'frameUrl4': '',
              'frameUrl5': '',
              'frameUrl6': '',
              'frameUrl7': '',
              'frameUrl8': '',
              'heartbeat': 60,
              'insecureUseHttp': False,
              'language': 'en',
              'nightMode': False,
              'scaleY': 'log',
              'secureCsp': False,
              'secureHstsHeader': True,
              'secureHstsHeaderIncludeSubdomains': False,
              'secureHstsHeaderPreload': False,
              'showClockDelta': False,
              'showClockLastTime': False,
              'showForecast': 'ar2',
              'showPlugins': 'dbsize delta direction upbat rawbg',
              'showRawbg': 'always',
              'theme': 'colors',
              'thresholds': {'bgHigh': 200,
                             'bgLow': 55,
                             'bgTargetBottom': 70,
                             'bgTargetTop': 170},
              'timeFormat': 12,
              'units': 'mg/dl'},
 'status': 'ok',
 'version': '14.2.5'}
Nightscout last uploaded basal: 
None
Nightscout last uploaded bolus: 
None
-----
Last basal start time: 2022-11-05 09:09:26-04:00 (0:24:41.536664 ago)
Last basal duration: 4.2
Last reading time: None (n/a)
-----
API errors occurred. Please check the errors above.
Created file tconnectsync-check-output.log containing additional debugging information.
For support, you can upload this file to https://github.com/jwoglom/tconnectsync/issues/new
The file -- but NOT the output printed above -- has been sanitized to remove sensitive data.
Please verify and remove any sensitive data, such as your Nightscout URL/secret and pump serial number,
as necessary.

**Additional context**

**Comment by GWTiger** [comment]
Wanted to +1 on this -- got the exact same error.

**Comment by jwoglom** [comment]
Hi @rehudson @GWTiger -- I believe this issue was solved in v0.8.4 released several months ago -- please upgrade to the latest release (currently v0.8.10)
