### ISSUE TITLE
Add rate when uploading temp basalt to nightscout

### ISSUE THREAD

**Issue by smatthew** [jwoglom/tconnectsync#7]
Can you add the "rate" field when uploading temp basal records to Nightscout? AutoTune needs that field to work properly.

Thanks!

**Comment by jwoglom** [comment]
I've been meaning to look into using autotune with my t:connect data, so thanks for pointing this out.

I'm not familiar with what exactly Autotune expects for this field -- is it equivalent to the "absolute" field which I'm currently propagating, which is just the rate in units/hr? (It's things like this that make me wish Nightscout data had a more rigid schema..)

https://github.com/jwoglom/tconnectsync/blob/c7aac1dca3b49a9f0a80f660a33ef8336d79f6a4/tconnectsync/parser/nightscout.py#L11

**Comment by smatthew** [comment]
I think you just need to include a value for "rate", which can be the same as the absolute field.
