### ISSUE TITLE
Heroku Free Resource causing app not to deploy

### ISSUE THREAD

**Issue by PerrynML** [jwoglom/tconnectsync#75]
Is there a way to change the resource from free dynos? I already have a paid Heroku account for CGM data. 

![image](https://user-images.githubusercontent.com/94065865/213276452-90b2ca1d-06a6-4e82-99c3-68f5dce58537.png)

![image](https://user-images.githubusercontent.com/94065865/213276526-e921a85a-87b8-4e7e-a5ee-8d878a05bb97.png)

**Comment by jwoglom** [comment]
I'm not sure but you might need to upgrade your subscription. I'm not actively running this on heroku (and given the free tier shutdown I don't run a testing instance of it anymore) so not fully sure where to go in the Heroku UI, but I see this when opening a free but shutdown heroku app:
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/192620/213820400-d7167f3c-9b33-4107-949e-33f0a1d659d7.png">

If you're paying for Heroku then presumably the best people to ask are Heroku support.

**Comment by jwoglom** [comment]
I updated the definition in the Heroku app.json file to use the eco plan by default, since the free plan is no longer available. That should hopefully solve this issue going forward.
