### ISSUE TITLE
Unable to Setup

### ISSUE THREAD

**Issue by MrJordanRoth** [jwoglom/tconnectsync#82]
**Describe the problem**
I'm following the directions to use a Docker install but when I run docker -run --env-file=.env tconnectsync --check-login I'm getting various issues. The t:connect API errors are related to HTTP 200 which says to check my username and password which I have done in the app and the website tconnect.tandemdiabetes.com. I do not see where the log file is actually written to the system as I cannot find tconnect-check-output.log anywhere to really troubleshoot this further. I've also noticed when looking at the output the NS_URL is only sending https:/url-to-nightscout and not https:// so I'm not sure if there is a code issue somewhere.

**To Reproduce**
1. Run the command docker -run --env-file=.env tconnectsync --check-login

**Expected behavior**
Expected to work or provide a more detailed error log file.

**Setup details**

* **Operating system:**  Ubuntu 22
* **tconnectsync version** (from `--version`): 0.9.3
* **On what platform are you using the t:connect mobile app?** (Android or iOS) Andriod
* **What version are you using of the t:connect mobile app?** 2.3

**Terminal output**
If applicable, add the full output from your terminal from running tconnectsync. Copy the output into a text editor like Textedit or Notepad first and find-and-replace sensitive strings, like your Nightscout URL and pump serial number, if they appear.

**Check Login output**
If applicable, please run `--check-login` and upload the tconnectsync-check-output.log file as an attachment on the issue. This file should have sensitive details like your Nightscout URL and pump serial number automatically removed, but double-check before uploading.

Unable to find the file.

This log will contain pump and CGM related information such as delivery events and blood sugars. If you would prefer to keep the contents private, send an email to tconnectsync<at>wogloms.net with the log output so @jwoglom can investigate.

**Additional context**

**Comment by MrJordanRoth** [comment]
I found the .ENV file works without the Apostrophe - with them I get API login errors on t:connect and the NS site.

# Your credentials for t:connect
TCONNECT_EMAIL=user@myemail.com
TCONNECT_PASSWORD=mytconnectpassword

# Your pump's serial number (numeric)
PUMP_SERIAL_NUMBER=theserialnumber

# URL of your Nightscout site
NS_URL=https://mynsurl/
# Your Nightscout API_SECRET value
NS_SECRET=mysecret

# Current timezone of the pump
TIMEZONE_NAME=America/New_York

**Comment by jwoglom** [comment]
I've added some improved logging around login failures. Confusingly, tconnect returns a HTTP 200 status code when your password is incorrect, so showing the status code in the error message is a bit confusing. Hope you were able to get it working!
