### ISSUE TITLE
Tier failure 

### ISSUE THREAD

**Issue by jojo805** [jwoglom/tconnectsync#83]
Deploying app on Heroku with paid eco dynos. 
Results error message.

uild app Show build log

Run scripts & scale dynos

Error scaling dynos: Process tier is invalid. Available process tiers are Eco, Basic, Production, Private, and Shield.

**Expected behavior**
Normal install per the warning that it will still work on paid accounts

**Have you followed the [Troubleshooting steps in the README?](https://github.com/jwoglom/tconnectsync-heroku#troubleshooting)** (Yes or No)

Yes

**Setup details**
Generic 

* **On what platform are you using the t:connect mobile app?** (Android or iOS)
* **What version are you using of the t:connect mobile app?**

Using heroku deployment.

**Heroku log output**
If applicable, add the full output from the heroku logs in More > View Logs. ([See the instructions in the README.](https://github.com/jwoglom/tconnectsync-heroku#testing))

**Check Login output**
If applicable, [please follow the instructions to visit the `check_login` page](https://github.com/jwoglom/tconnectsync-heroku#testing), and copy and paste the output here.

This file may contain sensitive details like your Nightscout URL and pump serial number. Copy the output into a text editor like Textedit or Notepad first and find-and-replace sensitive strings, like your Nightscout URL and pump serial number, if they appear.

The output will also contain pump and CGM related information such as delivery events and blood sugars. If you would prefer to keep the contents private, send an email to tconnectsync<at>wogloms.net with the log output so @jwoglom can investigate.

**Additional context**

**Comment by jwoglom** [comment]
@jojo805 I've fixed the configuration setting which caused this error. It no longer worked since Heroku sunset the free plan. I don't pay for Heroku currently, however, so I'm unable to test it.

**Comment by jojo805** [comment]
I will test it tomorrow
