### ISSUE TITLE
ControlIQ API HTTP 500 response

### ISSUE THREAD

**Issue by case-palmarium** [jwoglom/tconnectsync#85]
I've been running tconnectsync-heroku in Northflank successfully for about two weeks now, but a couple of days ago started receiving a HTTP 500 error and have stopped receiving data. Nothing has changed on my end, so I'm unsure how to further troubleshoot. 

I also installed tconnectsync on another machine and did a check login and received the same error. I've attached both log files.
[tconnectsync-7d4fbdb847-fvpdt_Invalid date-Invalid date.log](https://github.com/jwoglom/tconnectsync/files/12771924/tconnectsync-7d4fbdb847-fvpdt_Invalid.date-Invalid.date.log)
[tconnectsync-check-output.log](https://github.com/jwoglom/tconnectsync/files/12771927/tconnectsync-check-output.log)

EDIT this seems this resolved on its own, sorry.

**Comment by jwoglom** [comment]
Glad this is working for you now -- from the output it looks like tconnect was indeed returning 500s and also your Nightscout site returned `'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'`.

**Comment by case-palmarium** [comment]
That was my bad, I was testing on a machine behind a corporate proxy so expected that but forgot to cut it from the log file. Thanks!
