### ISSUE TITLE
support new t:connect API version: 7.17.1.2

### ISSUE THREAD

**Issue by MatthewMazaika** [jwoglom/tconnectsync#91]
2024-04-26 07:52:53 INFO     Reported tconnect software version: t:connect 7.17.1.2
2024-04-26 07:52:53 WARNING  Newer API version than last confirmed working. Saw t:connect 7.17.1.2 and expected t:connect 7.16.0.1

**Comment by AndyLow91** [comment]
I am also encountering the same issue. @jwoglom are you aware of this one? I can try to debug and contribute if/when i have the time, but you may be already on the case?

Here is the error I'm seeing that should be relevant:

```
Received ApiException in ControlIQApi with endpoint 'tconnect/controliq/api/therapytimeline/users/b3ccb839-1033-46d6-b67b-d271aaa4dc47?startDate=04-29-2024&endDate=04-30-2024' (tries 0): ControlIQ API HTTP 500 response:  (HTTP 500)
```

Maybe tandem have changed what their API is looking to receive in the request.

**Comment by jwoglom** [comment]
@AndyLow91 I've observed tconnectsync continue to work OK on my end -- I wonder if Tandem was just having an outage?

Looking through my own logs, I get a HTTP 500 from therapytimeline very irregularly and it seems to resolve itself.

```
./stdout.log:2024-04-12 06:02:43 WARNING  Received ApiException in ControlIQApi with endpoint 'tconnect/therapyevents/api/TherapyEvents/04-11-2024/04-12-2024/false?userId=xxxx' (tries 0): ControlIQ API HTTP 500 response: {"messages":["An error occurred. Try it again."]} (HTTP 500)
./stdout.log:2024-04-15 22:11:00 WARNING  Received ApiException in ControlIQApi with endpoint 'tconnect/therapyevents/api/TherapyEvents/04-14-2024/04-15-2024/false?userId=xxxx' (tries 0): ControlIQ API HTTP 500 response: {"messages":["An error occurred. Try it again."]} (HTTP 500)
./stdout.log:2024-04-22 20:11:04 WARNING  Received ApiException in ControlIQApi with endpoint 'tconnect/therapyevents/api/TherapyEvents/04-21-2024/04-22-2024/false?userId=xxxx' (tries 0): ControlIQ API HTTP 500 response: {"messages":["An error occurred. Try it again."]} (HTTP 500)
```

**Comment by jwoglom** [comment]
Closing, please re-open if you continue to experience issues

**Comment by MatthewMazaika** [comment]
I originally opened this ticket because the sync was working correctly even though it was giving the warning - since the current API version is working, should we update the warning message to no longer appear for this version?
