### ISSUE TITLE
2.0.2 fails to run with missing/failed jwt import

### ISSUE THREAD

**Issue by t1diotac** [jwoglom/tconnectsync#99]
**Describe the problem**
After upgrading to 2.0.2 using pip3, I get this when I try to run tconnectsync:

> Traceback (most recent call last):                                                                                                                    
>   File "/home/tsync/.local/bin/tconnectsync", line 5, in <module>                                                                                     
>     from tconnectsync import main                                                                                                                     
>   File "/home/tsync/.local/lib/python3.9/site-packages/tconnectsync/__init__.py", line 8, in <module>                                                 
>     from .api import TConnectApi                                                                                                                      
>   File "/home/tsync/.local/lib/python3.9/site-packages/tconnectsync/api/__init__.py", line 7, in <module>                                             
>     from .tandemsource import TandemSourceApi                                                                                                         
>   File "/home/tsync/.local/lib/python3.9/site-packages/tconnectsync/api/tandemsource.py", line 9, in <module>                                         
>     import jwt                                                                                                                                        
> ModuleNotFoundError: No module named 'jwt'

**To Reproduce**
1. /usr/bin/pip3 install --upgrade --user tconnectsync
2. ~/.local/bin/tconnectsync --features BASAL BOLUS PUMP_EVENTS PROFILES

**Expected behavior**
tconnectsync to do its normal run and update NightScout.

**Setup details**

* **Operating system: Rocky Linux 9.4** 
* **tconnectsync version** (from `--version`): 2.0.2 (but --version doesn't run, same error as above) 
* **On what platform are you using the t:connect mobile app?** iOS
* **What version are you using of the t:connect mobile app?** latest

**Additional context**
I was on 1.0.0 previously and it worked/ran as expected. Updated to 2.0.2 this morning, and the above issue presented.

**Comment by t1diotac** [comment]
Rolling back with:
`/usr/bin/pip3 install --user --force-reinstall "tconnectsync==1.0.0"`

worked, and re-upgrading again broke it again, so it seems fairly repeatable.

**Comment by jwoglom** [comment]
What python version are you using? @t1diotac 

This might be a side effect of the latest version of pyjwt only supporting >= python 3.8. I bumped a bunch of package versions in tconnectsync v2 and soft-dropped support for python 3.7 because more and more packages are no longer supporting it now that it's 6 years old.

**Comment by jwoglom** [comment]
Try to run `/usr/bin/pip3 install pyjwt==2.8.0` which is the latest version supporting python3.7 and see if that fixes it for you (https://github.com/jpadilla/pyjwt/releases/tag/2.8.0)

**Comment by jwoglom** [comment]
@t1diotac 
Ok this should be fixed now:

```
$ docker run --rm -it python:3.7 /bin/bash
root@77ff5625aa9e:/# pip install tconnectsync==2.0.6
root@77ff5625aa9e:/# tconnectsync --help
usage: tconnectsync [-h] [--version] [--pretend] [-v]
                    [--start-date START_DATE] [--end-date END_DATE]
                    [--days DAYS] [--auto-update] [--check-login]
                    [--features {BASAL,BOLUS,IOB,PUMP_EVENTS,PUMP_EVENTS_BASAL_SUSPENSION,PROFILES,CGM,CGM_ALERTS} [{BASAL,BOLUS,IOB,PUMP_EVENTS,PUMP_EVENTS_BASAL_SUSPENSION,PROFILES,CGM,CGM_ALERTS} ...]]
                    [--tandem-source]

Syncs bolus, basal, and IOB data from Tandem Diabetes t:connect to Nightscout.

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  --pretend             Pretend mode: do not upload any data to Nightscout.
  -v, --verbose         Verbose mode: show extra logging details
  --start-date START_DATE
                        The oldest date to process data from. Must be
                        specified with --end-date.
  --end-date END_DATE   The newest date to process data until (inclusive).
                        Must be specified with --start-date.
  --days DAYS           The number of days of t:connect data to read in.
                        Cannot be used with --from-date and --until-date.
  --auto-update         If set, continuously checks for updates from t:connect
                        and syncs with Nightscout.
  --check-login         If set, checks that the provided t:connect credentials
                        can be used to log in.
  --features {BASAL,BOLUS,IOB,PUMP_EVENTS,PUMP_EVENTS_BASAL_SUSPENSION,PROFILES,CGM,CGM_ALERTS} [{BASAL,BOLUS,IOB,PUMP_EVENTS,PUMP_EVENTS_BASAL_SUSPENSION,PROFILES,CGM,CGM_ALERTS} ...]
                        Specifies what data should be synchronized between
                        tconnect and Nightscout.
  --tandem-source       FOR TESTING: Use Tandem Source

Version 2.0.6
```

**Comment by t1diotac** [comment]
Fixed!! Thank you!

**Comment by t1diotac** [comment]
> What python version are you using? @t1diotac
> 
> This might be a side effect of the latest version of pyjwt only supporting >= python 3.8. I bumped a bunch of package versions in tconnectsync v2 and soft-dropped support for python 3.7 because more and more packages are no longer supporting it now that it's 6 years old.

For what it's worth, I'm running Python 3.9
